[package]
name = "fargo"
version = "0.2.0"
authors = ["Rob Tsuk <robtsuk@google.com>"]

[dependencies]
clap = "2"
failure = "0.1.1"
uname = "0.1.1"
notify = "4.0.0"

[[bin]]
name = "fargo"
doc = false

[workspace]
members = [ "cratest", "fargo-test",]
