[package]
name = "cratest"
version = "0.1.0"
authors = ["Tim Kilbourn <tkilbourn@google.com>"]

[dependencies]
clap = "2"
git2 = "0.6"
rayon = "0.8"
reqwest = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tempdir = "0.3"
